##################################################################################
# Makefile - Configuration file for GNU make (http://www.gnu.org/software/make/)
# Time-stamp: <Mar 2013-04-02 10:45 svarrette>
#
# Copyright (c) 2013 Sebastien Varrette <Sebastien.Varrette@uni.lu>
#               http://varrette.gforge.uni.lu
##################################################################################

all: 
	$(MAKE) -C ../ 

%:
	$(MAKE) -C ../ $@
